name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Ver la hora
        run: echo %date%

      - name: Esperar 3 segundos
        run: powershell -Command "Start-Sleep -Seconds 3"